version: '3'

services:
 steam:
  image: postgres:alpine
  ports:
  - '5432:5432'
  container_name: 'steamecommerce'
  restart: always
  volumes:
   - netflixpg-data:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: jklv1234

volumes:
 netflixpg-data: